<?php

namespace Konst\UploaderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilesOnServersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesOnServersRepository extends EntityRepository
{
}
