<?php

namespace Konst\UploaderBundle\Repository;

/**
 * FilesOnServersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesOnServersRepository extends \Doctrine\ORM\EntityRepository
{
}
